/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ActionRouteImport } from './routes/action'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as CognitionRouteImport } from './routes/cognition'
import { Route as OrchestratorRouteImport } from './routes/orchestrator'
import { Route as OverviewRouteImport } from './routes/overview'
import { Route as PerceptionRouteImport } from './routes/perception'
import { Route as SimulationRouteImport } from './routes/simulation'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActionRoute = ActionRouteImport.update({
  id: '/action',
  path: '/action',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const CognitionRoute = CognitionRouteImport.update({
  id: '/cognition',
  path: '/cognition',
  getParentRoute: () => rootRouteImport,
} as any)
const OrchestratorRoute = OrchestratorRouteImport.update({
  id: '/orchestrator',
  path: '/orchestrator',
  getParentRoute: () => rootRouteImport,
} as any)
const OverviewRoute = OverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => rootRouteImport,
} as any)
const PerceptionRoute = PerceptionRouteImport.update({
  id: '/perception',
  path: '/perception',
  getParentRoute: () => rootRouteImport,
} as any)
const SimulationRoute = SimulationRouteImport.update({
  id: '/simulation',
  path: '/simulation',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/action': typeof ActionRoute
  '/audit': typeof AuditRoute
  '/cognition': typeof CognitionRoute
  '/orchestrator': typeof OrchestratorRoute
  '/overview': typeof OverviewRoute
  '/perception': typeof PerceptionRoute
  '/simulation': typeof SimulationRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/action': typeof ActionRoute
  '/audit': typeof AuditRoute
  '/cognition': typeof CognitionRoute
  '/orchestrator': typeof OrchestratorRoute
  '/overview': typeof OverviewRoute
  '/perception': typeof PerceptionRoute
  '/simulation': typeof SimulationRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/action': typeof ActionRoute
  '/audit': typeof AuditRoute
  '/cognition': typeof CognitionRoute
  '/orchestrator': typeof OrchestratorRoute
  '/overview': typeof OverviewRoute
  '/perception': typeof PerceptionRoute
  '/simulation': typeof SimulationRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/action'
    | '/audit'
    | '/cognition'
    | '/orchestrator'
    | '/overview'
    | '/perception'
    | '/simulation'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/action'
    | '/audit'
    | '/cognition'
    | '/orchestrator'
    | '/overview'
    | '/perception'
    | '/simulation'
  id:
    | '__root__'
    | '/'
    | '/action'
    | '/audit'
    | '/cognition'
    | '/orchestrator'
    | '/overview'
    | '/perception'
    | '/simulation'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActionRoute: typeof ActionRoute
  AuditRoute: typeof AuditRoute
  CognitionRoute: typeof CognitionRoute
  OrchestratorRoute: typeof OrchestratorRoute
  OverviewRoute: typeof OverviewRoute
  PerceptionRoute: typeof PerceptionRoute
  SimulationRoute: typeof SimulationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/action': {
      id: '/action'
      path: '/action'
      fullPath: '/action'
      preLoaderRoute: typeof ActionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cognition': {
      id: '/cognition'
      path: '/cognition'
      fullPath: '/cognition'
      preLoaderRoute: typeof CognitionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orchestrator': {
      id: '/orchestrator'
      path: '/orchestrator'
      fullPath: '/orchestrator'
      preLoaderRoute: typeof OrchestratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/overview': {
      id: '/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof OverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perception': {
      id: '/perception'
      path: '/perception'
      fullPath: '/perception'
      preLoaderRoute: typeof PerceptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulation': {
      id: '/simulation'
      path: '/simulation'
      fullPath: '/simulation'
      preLoaderRoute: typeof SimulationRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActionRoute: ActionRoute,
  AuditRoute: AuditRoute,
  CognitionRoute: CognitionRoute,
  OrchestratorRoute: OrchestratorRoute,
  OverviewRoute: OverviewRoute,
  PerceptionRoute: PerceptionRoute,
  SimulationRoute: SimulationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
